#!/usr/bin/ksh -p

source ../basic/test.cfg

typeset nprd1=${NPRD_A}
typeset nprd2=${NPRD_B}
typeset iod=${IOD}
typeset password=${SOURCE_DOMAIN_PASSWORD}
typeset logfile=$(echo ${LOGPATH}/func_05_reboot)
typeset i=0

nprd1_name=$(python ../basic/python/ior.py -d ${nprd1} -p ${password} -r 'hostname')
print "NPRD1:${nprd1_name}"

nprd2_name=$(python ../basic/python/ior.py -d ${nprd2} -p ${password} -r 'hostname')
print "NPRD2:${nprd2_name}"

iod_name=$(python ../basic/python/ior.py -d ${iod} -p ${password} -r 'hostname')
print "IOD:${iod_name}"

python ../basic/python/ior.py -d ${iod} -p ${password} -s 'test -f run_io.sh'
flag=$(python ../basic/python/ior.py -d ${iod} -p ${password} -r 'echo $?')
if [[ ${flag} -ne 0 ]];then
    print "Distributing run_io.sh to ${iod}"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "touch run_io.sh"    
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'while(true)' >> run_io.sh"    
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'do' >> run_io.sh"   
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'mkfile 500m /ior_pool/fs/fcior_test' >> run_io.sh"   
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'sleep 1' >> run_io.sh"   
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'mv /ior_pool/fs/iorfc_test /export/home/' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'sleep 1' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'rm -f /ior_pool/fs/iorfc_test' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'sleep 1' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'mv /export/home/iorfc_test /ior_pool/fs/' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'sleep 1' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'rm -f /ior_pool/fs/iorfc_test' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'sleep 1' >> run_io.sh"
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "echo 'done' >> run_io.sh"   
    python ../basic/python/ior.py -d ${iod} -p ${password} -r "chmod +x run_io.sh"
    print "Done"
fi
rm -f ${logfile}
test -d ${LOGPATH}
if [ $? -ne 0 ];then
    mkdir -p ${LOGPATH}
fi
touch ${logfile}

ldm list-io|grep ${iod} > ${logfile}
echo " " >> ${logfile}

python ../basic/python/ior.py -d ${iod} -p ${password} -r 'hotplug list -lv' -l ${logfile}
echo "\n\n\n" >> ${logfile}

print "Rebooting ${nprd1}..."
echo "---------------------" >> ${logfile}
python ../basic/python/ior.py -d ${nprd1} -p ${password} --reboot &
echo "reboot ${nprd1}" >> ${logfile}
echo "---------------------" >> ${logfile}
echo "\n\n\n" >> ${logfile}

sleep 10

print "Begin test"
while [[ $i -lt 10 ]];do
    python ../basic/python/ior.py -d ${iod} -p ${password} -r 'hotplug list -lv' -l ${logfile}
    echo " " >> ${logfile}
    python ../basic/python/ior.py -d ${iod} -p ${password} -r 'iostat -xn 2 3' -l ${logfile}
    echo " " >> ${logfile}
    #python ../basic/python/ior.py -d ${iod} -p ${password} -r 'fcinfo hab-port|grep HBA' -l ${logfile}
    #echo " " >> ${logfile}
    i=$(($i + 1))
    sleep 15
done
print "Done"
