#!/usr/bin/ksh -p

. ../basic/common.kshlib

source ../basic/test.cfg

typeset pf1=${PF_A}

typeset iod=${IOD}
typeset nprd1=${NPRD_A}

tmpfile=$(mktemp)
ldm list-io |grep ${iod} |perl -e 'print reverse <>' > ${tmpfile}

while read uvf nVF nbus udomain;do
    ldm rm-io ${uvf} ${udomain}
    if [[ $? -ne 0 ]];then
          return 1
    else
          print "Remove ${uvf} from ${udomain} success"
    fi
done < ${tmpfile}

count_vf_pf1=$(ldm list-io|grep "${pf1}\."|wc -l)
if [[ ${count_vf_pf1} -ne 0 ]];then
    print "Destroying the VFs created on ${pf1}"
    ldm destroy-vf -n max ${pf1}
    [[ $? -ne 0 ]] && print "Fail" && return 1
    print "Done"
fi

