#!/usr/bin/ksh -p

. ../basic/common.kshlib

source ../basic/test.cfg

typeset pf1=${PF_A}
typeset pf2=${PF_B}

typeset iod=${IOD}

python ../basic/python/ior.py -d ${iod} -p ${password} -s "ps -ef|grep vdbench|grep -v grep|awk '{print $2}'|xargs kill -9"

#Destroy all the VFs which have been created
tmpfile=$(mktemp)
ldm list-io|grep "${pf1}\.VF" > ${tmpfile}
if [[ $? -eq 0 ]];then
    while read uvf nVF nBUS udomain;do
        if [[ ${udomain} != "" ]];then
              ldm rm-io ${uvf} ${udomain}
              sleep 3
        fi
    done < ${tmpfile}
    ldm destroy-vf -n max ${pf1}
fi

tmpfile1=$(mktemp)
ldm list-io|grep "${pf2}\.VF" > ${tmpfile1}
if [[ $? -eq 0 ]];then
    while read uvf nVF nBUS udomain;do
        if [[ ${udomain} != "" ]];then
              ldm rm-io ${uvf} ${udomain}
              sleep 3
        fi
    done < ${tmpfile}
    ldm destroy-vf -n max ${pf2}
fi

re_pf1=${pf1//\//\\\/}
re_pf1=${re_pf1/\./\\\.}
cmd_get_pf_line=$(echo "ldm list-io -l|sed -n '/${re_pf1} /='")
pf_line_num=$(eval ${cmd_get_pf_line})
maxvfs_line_num=$((${pf_line_num} + 2))
#maxvfs=$(eval "ldm list-io -l|sed -n '${maxvfs_line_num}p'|awk -F'=' '{print $2}'")
maxvfs_equation=$(eval "ldm list-io -l|sed -n '${maxvfs_line_num}p'")
maxvfs_count=$(echo ${maxvfs_equation}|awk -F'=' '{print $2}')
maxvfs_pf1=`expr ${maxvfs_count} - 1`

re_pf2=${pf2//\//\\\/}
re_pf2=${re_pf2/\./\\\.}
cmd_get_pf_line=$(echo "ldm list-io -l|sed -n '/${re_pf2} /='")
pf_line_num=$(eval ${cmd_get_pf_line})
maxvfs_line_num=$((${pf_line_num} + 2))
#maxvfs=$(eval "ldm list-io -l|sed -n '${maxvfs_line_num}p'|awk -F'=' '{print $2}'")
maxvfs_equation=$(eval "ldm list-io -l|sed -n '${maxvfs_line_num}p'")
maxvfs_count=$(echo ${maxvfs_equation}|awk -F'=' '{print $2}')
maxvfs_pf2=`expr ${maxvfs_count} -1`

if [[ ${maxvfs_pf1} -le ${maxvfs_pf2} ]];then
    maxvfs=${maxvfs_pf1}
fi
(( maxvfs-- ))
for i in {0..$maxvfs}
do
    destroyed_iod=$(echo \${IOD$i})
    destroy_domain ${destroyed_iod}
done
