#!/usr/bin/ksh -p

. ../basic/common.kshlib

source ../basic/test.cfg

typeset pf1=${PF_A}
typeset pf2=${PF_A}

typeset iod=${IOD}
typeset nprd1=${NPRD_A}
typeset nprd2=${NPRD_B}

python ../basic/python/ior.py -d ${iod} -p ${password} -s "ps -ef|grep run_io.sh|grep -v grep|awk '{print $2}'|xargs kill -9"
python ../basic/python/ior.py -d ${iod} -p ${password} -s "zfs destroy ior_pool/fs"
python ../basic/python/ior.py -d ${iod} -p ${password} -s "zpool destroy -f ior_pool"

tmpfile=$(mktemp)
ldm list-io |grep ${iod} |perl -e 'print reverse <>' > ${tmpfile}
while read uvf nVF nbus udomain;do
    ldm rm-io ${uvf} ${udomain}
    if [[ $? -ne 0 ]];then
        return 1
    else
        print "Remove ${uvf} from ${udomain} success"
        ldm destroy-vf ${uvf}
    fi
done < ${tmpfile}

