#!/usr/bin/ksh -p

pf=$1
domain=$2

maxvfs=""
maxvfs_equation=$(ldm list-io -l -p /SYS/MB/PCIE3/IOVFC.PF0|grep maxvfs|cut -d'|' -f3)
eval $maxvfs_equation

for i in {0..$((maxvfs-1))};do
    ldm add-io ${pf}.VF$i $domain
    sleep 1
done

